version: '3.8'
name: expense
networks:
  default:
    name: expense
volumes:
  mysqldb:
    external: true
services:
  mysql:
    image: chandureddy08/mysql:v1.0
    container_name: mysql
    volumes:
      - source: mysqldb
        target: /var/lib/mysql
        type: volume
  backend:
    image: chandureddy08/backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: chandureddy08/frontend:v1.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend